/**
 * Error Constants
 * Standardized error codes and messages
 */

export const ERROR_CODES = {
  // Authentication Errors
  INVALID_CREDENTIALS: 'INVALID_CREDENTIALS',
  TOKEN_EXPIRED: 'TOKEN_EXPIRED',
  TOKEN_INVALID: 'TOKEN_INVALID',
  UNAUTHORIZED: 'UNAUTHORIZED',
  FORBIDDEN: 'FORBIDDEN',
  SESSION_EXPIRED: 'SESSION_EXPIRED',
  
  // Validation Errors
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  MISSING_REQUIRED_FIELD: 'MISSING_REQUIRED_FIELD',
  INVALID_FORMAT: 'INVALID_FORMAT',
  INVALID_VALUE: 'INVALID_VALUE',
  INVALID_EMAIL: 'INVALID_EMAIL',
  INVALID_PASSWORD: 'INVALID_PASSWORD',
  PASSWORD_TOO_WEAK: 'PASSWORD_TOO_WEAK',
  
  // Resource Errors
  RESOURCE_NOT_FOUND: 'RESOURCE_NOT_FOUND',
  RESOURCE_ALREADY_EXISTS: 'RESOURCE_ALREADY_EXISTS',
  RESOURCE_CONFLICT: 'RESOURCE_CONFLICT',
  RESOURCE_LOCKED: 'RESOURCE_LOCKED',
  
  // Platform Errors
  PLATFORM_NOT_SUPPORTED: 'PLATFORM_NOT_SUPPORTED',
  PLATFORM_API_ERROR: 'PLATFORM_API_ERROR',
  PLATFORM_RATE_LIMITED: 'PLATFORM_RATE_LIMITED',
  PLATFORM_UNAUTHORIZED: 'PLATFORM_UNAUTHORIZED',
  PLATFORM_FORBIDDEN: 'PLATFORM_FORBIDDEN',
  PLATFORM_SERVICE_UNAVAILABLE: 'PLATFORM_SERVICE_UNAVAILABLE',
  ACCOUNT_NOT_CONNECTED: 'ACCOUNT_NOT_CONNECTED',
  ACCOUNT_EXPIRED: 'ACCOUNT_EXPIRED',
  ACCOUNT_SUSPENDED: 'ACCOUNT_SUSPENDED',
  
  // Business Logic Errors
  SUBSCRIPTION_REQUIRED: 'SUBSCRIPTION_REQUIRED',
  SUBSCRIPTION_EXPIRED: 'SUBSCRIPTION_EXPIRED',
  FEATURE_NOT_AVAILABLE: 'FEATURE_NOT_AVAILABLE',
  LIMIT_EXCEEDED: 'LIMIT_EXCEEDED',
  QUOTA_EXCEEDED: 'QUOTA_EXCEEDED',
  INSUFFICIENT_PERMISSIONS: 'INSUFFICIENT_PERMISSIONS',
  
  // File Upload Errors
  FILE_TOO_LARGE: 'FILE_TOO_LARGE',
  FILE_TYPE_NOT_SUPPORTED: 'FILE_TYPE_NOT_SUPPORTED',
  FILE_UPLOAD_FAILED: 'FILE_UPLOAD_FAILED',
  FILE_NOT_FOUND: 'FILE_NOT_FOUND',
  FILE_CORRUPTED: 'FILE_CORRUPTED',
  
  // System Errors
  INTERNAL_ERROR: 'INTERNAL_ERROR',
  DATABASE_ERROR: 'DATABASE_ERROR',
  EXTERNAL_SERVICE_ERROR: 'EXTERNAL_SERVICE_ERROR',
  NETWORK_ERROR: 'NETWORK_ERROR',
  TIMEOUT_ERROR: 'TIMEOUT_ERROR',
  SERVICE_UNAVAILABLE: 'SERVICE_UNAVAILABLE',
  MAINTENANCE_MODE: 'MAINTENANCE_MODE',
  
  // Rate Limiting
  RATE_LIMIT_EXCEEDED: 'RATE_LIMIT_EXCEEDED',
  TOO_MANY_REQUESTS: 'TOO_MANY_REQUESTS',
  
  // OAuth Errors
  OAUTH_ERROR: 'OAUTH_ERROR',
  OAUTH_INVALID_REQUEST: 'OAUTH_INVALID_REQUEST',
  OAUTH_INVALID_CLIENT: 'OAUTH_INVALID_CLIENT',
  OAUTH_INVALID_GRANT: 'OAUTH_INVALID_GRANT',
  OAUTH_UNAUTHORIZED_CLIENT: 'OAUTH_UNAUTHORIZED_CLIENT',
  OAUTH_UNSUPPORTED_GRANT_TYPE: 'OAUTH_UNSUPPORTED_GRANT_TYPE',
  OAUTH_INVALID_SCOPE: 'OAUTH_INVALID_SCOPE',
  OAUTH_ACCESS_DENIED: 'OAUTH_ACCESS_DENIED',
  
  // Webhook Errors
  WEBHOOK_VERIFICATION_FAILED: 'WEBHOOK_VERIFICATION_FAILED',
  WEBHOOK_PROCESSING_FAILED: 'WEBHOOK_PROCESSING_FAILED',
  WEBHOOK_INVALID_PAYLOAD: 'WEBHOOK_INVALID_PAYLOAD',
  WEBHOOK_SIGNATURE_INVALID: 'WEBHOOK_SIGNATURE_INVALID',
} as const;

export const ERROR_MESSAGES = {
  [ERROR_CODES.INVALID_CREDENTIALS]: 'Invalid email or password',
  [ERROR_CODES.TOKEN_EXPIRED]: 'Access token has expired',
  [ERROR_CODES.TOKEN_INVALID]: 'Invalid access token',
  [ERROR_CODES.UNAUTHORIZED]: 'Authentication required',
  [ERROR_CODES.FORBIDDEN]: 'Access denied',
  [ERROR_CODES.SESSION_EXPIRED]: 'Session has expired, please login again',
  
  [ERROR_CODES.VALIDATION_ERROR]: 'Validation failed',
  [ERROR_CODES.MISSING_REQUIRED_FIELD]: 'Required field is missing',
  [ERROR_CODES.INVALID_FORMAT]: 'Invalid format',
  [ERROR_CODES.INVALID_VALUE]: 'Invalid value',
  [ERROR_CODES.INVALID_EMAIL]: 'Invalid email address',
  [ERROR_CODES.INVALID_PASSWORD]: 'Invalid password',
  [ERROR_CODES.PASSWORD_TOO_WEAK]: 'Password is too weak',
  
  [ERROR_CODES.RESOURCE_NOT_FOUND]: 'Resource not found',
  [ERROR_CODES.RESOURCE_ALREADY_EXISTS]: 'Resource already exists',
  [ERROR_CODES.RESOURCE_CONFLICT]: 'Resource conflict',
  [ERROR_CODES.RESOURCE_LOCKED]: 'Resource is locked',
  
  [ERROR_CODES.PLATFORM_NOT_SUPPORTED]: 'Platform is not supported',
  [ERROR_CODES.PLATFORM_API_ERROR]: 'Platform API error',
  [ERROR_CODES.PLATFORM_RATE_LIMITED]: 'Platform rate limit exceeded',
  [ERROR_CODES.PLATFORM_UNAUTHORIZED]: 'Platform authorization failed',
  [ERROR_CODES.PLATFORM_FORBIDDEN]: 'Platform access forbidden',
  [ERROR_CODES.PLATFORM_SERVICE_UNAVAILABLE]: 'Platform service unavailable',
  [ERROR_CODES.ACCOUNT_NOT_CONNECTED]: 'Account is not connected',
  [ERROR_CODES.ACCOUNT_EXPIRED]: 'Account access has expired',
  [ERROR_CODES.ACCOUNT_SUSPENDED]: 'Account has been suspended',
  
  [ERROR_CODES.SUBSCRIPTION_REQUIRED]: 'Subscription required',
  [ERROR_CODES.SUBSCRIPTION_EXPIRED]: 'Subscription has expired',
  [ERROR_CODES.FEATURE_NOT_AVAILABLE]: 'Feature not available in your plan',
  [ERROR_CODES.LIMIT_EXCEEDED]: 'Limit exceeded',
  [ERROR_CODES.QUOTA_EXCEEDED]: 'Quota exceeded',
  [ERROR_CODES.INSUFFICIENT_PERMISSIONS]: 'Insufficient permissions',
  
  [ERROR_CODES.FILE_TOO_LARGE]: 'File size exceeds maximum limit',
  [ERROR_CODES.FILE_TYPE_NOT_SUPPORTED]: 'File type not supported',
  [ERROR_CODES.FILE_UPLOAD_FAILED]: 'File upload failed',
  [ERROR_CODES.FILE_NOT_FOUND]: 'File not found',
  [ERROR_CODES.FILE_CORRUPTED]: 'File is corrupted',
  
  [ERROR_CODES.INTERNAL_ERROR]: 'Internal server error',
  [ERROR_CODES.DATABASE_ERROR]: 'Database error',
  [ERROR_CODES.EXTERNAL_SERVICE_ERROR]: 'External service error',
  [ERROR_CODES.NETWORK_ERROR]: 'Network error',
  [ERROR_CODES.TIMEOUT_ERROR]: 'Request timeout',
  [ERROR_CODES.SERVICE_UNAVAILABLE]: 'Service unavailable',
  [ERROR_CODES.MAINTENANCE_MODE]: 'Service is under maintenance',
  
  [ERROR_CODES.RATE_LIMIT_EXCEEDED]: 'Rate limit exceeded',
  [ERROR_CODES.TOO_MANY_REQUESTS]: 'Too many requests',
  
  [ERROR_CODES.OAUTH_ERROR]: 'OAuth error',
  [ERROR_CODES.OAUTH_INVALID_REQUEST]: 'Invalid OAuth request',
  [ERROR_CODES.OAUTH_INVALID_CLIENT]: 'Invalid OAuth client',
  [ERROR_CODES.OAUTH_INVALID_GRANT]: 'Invalid OAuth grant',
  [ERROR_CODES.OAUTH_UNAUTHORIZED_CLIENT]: 'Unauthorized OAuth client',
  [ERROR_CODES.OAUTH_UNSUPPORTED_GRANT_TYPE]: 'Unsupported grant type',
  [ERROR_CODES.OAUTH_INVALID_SCOPE]: 'Invalid OAuth scope',
  [ERROR_CODES.OAUTH_ACCESS_DENIED]: 'OAuth access denied',
  
  [ERROR_CODES.WEBHOOK_VERIFICATION_FAILED]: 'Webhook verification failed',
  [ERROR_CODES.WEBHOOK_PROCESSING_FAILED]: 'Webhook processing failed',
  [ERROR_CODES.WEBHOOK_INVALID_PAYLOAD]: 'Invalid webhook payload',
  [ERROR_CODES.WEBHOOK_SIGNATURE_INVALID]: 'Invalid webhook signature',
} as const;

export const HTTP_STATUS_CODES = {
  OK: 200,
  CREATED: 201,
  ACCEPTED: 202,
  NO_CONTENT: 204,
  BAD_REQUEST: 400,
  UNAUTHORIZED: 401,
  FORBIDDEN: 403,
  NOT_FOUND: 404,
  METHOD_NOT_ALLOWED: 405,
  CONFLICT: 409,
  UNPROCESSABLE_ENTITY: 422,
  TOO_MANY_REQUESTS: 429,
  INTERNAL_SERVER_ERROR: 500,
  BAD_GATEWAY: 502,
  SERVICE_UNAVAILABLE: 503,
  GATEWAY_TIMEOUT: 504,
} as const;

export const ERROR_CATEGORIES = {
  AUTHENTICATION: 'authentication',
  AUTHORIZATION: 'authorization',
  VALIDATION: 'validation',
  RESOURCE: 'resource',
  PLATFORM: 'platform',
  BUSINESS: 'business',
  SYSTEM: 'system',
  NETWORK: 'network',
  RATE_LIMIT: 'rate_limit',
  OAUTH: 'oauth',
  WEBHOOK: 'webhook',
  FILE: 'file',
} as const;

export const RETRY_STRATEGIES = {
  EXPONENTIAL_BACKOFF: 'exponential_backoff',
  LINEAR_BACKOFF: 'linear_backoff',
  FIXED_DELAY: 'fixed_delay',
  NO_RETRY: 'no_retry',
} as const;

export const DEFAULT_RETRY_CONFIG = {
  maxRetries: 3,
  baseDelay: 1000, // 1 second
  maxDelay: 30000, // 30 seconds
  strategy: RETRY_STRATEGIES.EXPONENTIAL_BACKOFF,
  retryableErrors: [
    ERROR_CODES.NETWORK_ERROR,
    ERROR_CODES.TIMEOUT_ERROR,
    ERROR_CODES.SERVICE_UNAVAILABLE,
    ERROR_CODES.PLATFORM_SERVICE_UNAVAILABLE,
    ERROR_CODES.RATE_LIMIT_EXCEEDED,
  ],
} as const;