/**
 * Permission Constants
 * Role-based access control permissions
 */

export const PERMISSIONS = {
  // User Management
  USER_CREATE: 'user:create',
  USER_READ: 'user:read',
  USER_UPDATE: 'user:update',
  USER_DELETE: 'user:delete',
  USER_LIST: 'user:list',
  USER_INVITE: 'user:invite',
  USER_ROLE_CHANGE: 'user:role_change',
  
  // Platform Account Management
  ACCOUNT_CONNECT: 'account:connect',
  ACCOUNT_DISCONNECT: 'account:disconnect',
  ACCOUNT_READ: 'account:read',
  ACCOUNT_UPDATE: 'account:update',
  ACCOUNT_LIST: 'account:list',
  ACCOUNT_REFRESH_TOKEN: 'account:refresh_token',
  
  // Content Management
  POST_CREATE: 'post:create',
  POST_READ: 'post:read',
  POST_UPDATE: 'post:update',
  POST_DELETE: 'post:delete',
  POST_PUBLISH: 'post:publish',
  POST_SCHEDULE: 'post:schedule',
  POST_LIST: 'post:list',
  POST_ANALYTICS: 'post:analytics',
  
  // Message Management
  MESSAGE_READ: 'message:read',
  MESSAGE_SEND: 'message:send',
  MESSAGE_DELETE: 'message:delete',
  MESSAGE_LIST: 'message:list',
  MESSAGE_AUTO_REPLY: 'message:auto_reply',
  MESSAGE_TEMPLATE: 'message:template',
  
  // Template Management
  TEMPLATE_CREATE: 'template:create',
  TEMPLATE_READ: 'template:read',
  TEMPLATE_UPDATE: 'template:update',
  TEMPLATE_DELETE: 'template:delete',
  TEMPLATE_LIST: 'template:list',
  TEMPLATE_USE: 'template:use',
  
  // Analytics
  ANALYTICS_READ: 'analytics:read',
  ANALYTICS_EXPORT: 'analytics:export',
  ANALYTICS_REPORT: 'analytics:report',
  ANALYTICS_DASHBOARD: 'analytics:dashboard',
  
  // Automation
  AUTOMATION_CREATE: 'automation:create',
  AUTOMATION_READ: 'automation:read',
  AUTOMATION_UPDATE: 'automation:update',
  AUTOMATION_DELETE: 'automation:delete',
  AUTOMATION_EXECUTE: 'automation:execute',
  AUTOMATION_LIST: 'automation:list',
  
  // Campaign Management
  CAMPAIGN_CREATE: 'campaign:create',
  CAMPAIGN_READ: 'campaign:read',
  CAMPAIGN_UPDATE: 'campaign:update',
  CAMPAIGN_DELETE: 'campaign:delete',
  CAMPAIGN_START: 'campaign:start',
  CAMPAIGN_PAUSE: 'campaign:pause',
  CAMPAIGN_STOP: 'campaign:stop',
  CAMPAIGN_LIST: 'campaign:list',
  
  // Webhook Management
  WEBHOOK_CREATE: 'webhook:create',
  WEBHOOK_READ: 'webhook:read',
  WEBHOOK_UPDATE: 'webhook:update',
  WEBHOOK_DELETE: 'webhook:delete',
  WEBHOOK_LIST: 'webhook:list',
  WEBHOOK_TEST: 'webhook:test',
  
  // File Management
  FILE_UPLOAD: 'file:upload',
  FILE_READ: 'file:read',
  FILE_DELETE: 'file:delete',
  FILE_LIST: 'file:list',
  FILE_DOWNLOAD: 'file:download',
  
  // Subscription Management
  SUBSCRIPTION_READ: 'subscription:read',
  SUBSCRIPTION_UPDATE: 'subscription:update',
  SUBSCRIPTION_CANCEL: 'subscription:cancel',
  SUBSCRIPTION_BILLING: 'subscription:billing',
  
  // Admin Permissions
  ADMIN_USER_MANAGEMENT: 'admin:user_management',
  ADMIN_SYSTEM_CONFIG: 'admin:system_config',
  ADMIN_PLATFORM_CONFIG: 'admin:platform_config',
  ADMIN_ANALYTICS: 'admin:analytics',
  ADMIN_LOGS: 'admin:logs',
  ADMIN_MAINTENANCE: 'admin:maintenance',
  ADMIN_BILLING: 'admin:billing',
  
  // System Permissions
  SYSTEM_HEALTH: 'system:health',
  SYSTEM_METRICS: 'system:metrics',
  SYSTEM_LOGS: 'system:logs',
  SYSTEM_CONFIG: 'system:config',
} as const;

export const ROLES = {
  SUPER_ADMIN: 'super_admin',
  ADMIN: 'admin',
  MANAGER: 'manager',
  USER: 'user',
  VIEWER: 'viewer',
  API_CLIENT: 'api_client',
} as const;

export const ROLE_PERMISSIONS = {
  [ROLES.SUPER_ADMIN]: [
    // All permissions
    ...Object.values(PERMISSIONS),
  ],
  
  [ROLES.ADMIN]: [
    // User Management
    PERMISSIONS.USER_CREATE,
    PERMISSIONS.USER_READ,
    PERMISSIONS.USER_UPDATE,
    PERMISSIONS.USER_DELETE,
    PERMISSIONS.USER_LIST,
    PERMISSIONS.USER_INVITE,
    PERMISSIONS.USER_ROLE_CHANGE,
    
    // Platform Account Management
    PERMISSIONS.ACCOUNT_CONNECT,
    PERMISSIONS.ACCOUNT_DISCONNECT,
    PERMISSIONS.ACCOUNT_READ,
    PERMISSIONS.ACCOUNT_UPDATE,
    PERMISSIONS.ACCOUNT_LIST,
    PERMISSIONS.ACCOUNT_REFRESH_TOKEN,
    
    // Content Management
    PERMISSIONS.POST_CREATE,
    PERMISSIONS.POST_READ,
    PERMISSIONS.POST_UPDATE,
    PERMISSIONS.POST_DELETE,
    PERMISSIONS.POST_PUBLISH,
    PERMISSIONS.POST_SCHEDULE,
    PERMISSIONS.POST_LIST,
    PERMISSIONS.POST_ANALYTICS,
    
    // Message Management
    PERMISSIONS.MESSAGE_READ,
    PERMISSIONS.MESSAGE_SEND,
    PERMISSIONS.MESSAGE_DELETE,
    PERMISSIONS.MESSAGE_LIST,
    PERMISSIONS.MESSAGE_AUTO_REPLY,
    PERMISSIONS.MESSAGE_TEMPLATE,
    
    // Template Management
    PERMISSIONS.TEMPLATE_CREATE,
    PERMISSIONS.TEMPLATE_READ,
    PERMISSIONS.TEMPLATE_UPDATE,
    PERMISSIONS.TEMPLATE_DELETE,
    PERMISSIONS.TEMPLATE_LIST,
    PERMISSIONS.TEMPLATE_USE,
    
    // Analytics
    PERMISSIONS.ANALYTICS_READ,
    PERMISSIONS.ANALYTICS_EXPORT,
    PERMISSIONS.ANALYTICS_REPORT,
    PERMISSIONS.ANALYTICS_DASHBOARD,
    
    // Automation
    PERMISSIONS.AUTOMATION_CREATE,
    PERMISSIONS.AUTOMATION_READ,
    PERMISSIONS.AUTOMATION_UPDATE,
    PERMISSIONS.AUTOMATION_DELETE,
    PERMISSIONS.AUTOMATION_EXECUTE,
    PERMISSIONS.AUTOMATION_LIST,
    
    // Campaign Management
    PERMISSIONS.CAMPAIGN_CREATE,
    PERMISSIONS.CAMPAIGN_READ,
    PERMISSIONS.CAMPAIGN_UPDATE,
    PERMISSIONS.CAMPAIGN_DELETE,
    PERMISSIONS.CAMPAIGN_START,
    PERMISSIONS.CAMPAIGN_PAUSE,
    PERMISSIONS.CAMPAIGN_STOP,
    PERMISSIONS.CAMPAIGN_LIST,
    
    // Webhook Management
    PERMISSIONS.WEBHOOK_CREATE,
    PERMISSIONS.WEBHOOK_READ,
    PERMISSIONS.WEBHOOK_UPDATE,
    PERMISSIONS.WEBHOOK_DELETE,
    PERMISSIONS.WEBHOOK_LIST,
    PERMISSIONS.WEBHOOK_TEST,
    
    // File Management
    PERMISSIONS.FILE_UPLOAD,
    PERMISSIONS.FILE_READ,
    PERMISSIONS.FILE_DELETE,
    PERMISSIONS.FILE_LIST,
    PERMISSIONS.FILE_DOWNLOAD,
    
    // Admin Permissions
    PERMISSIONS.ADMIN_USER_MANAGEMENT,
    PERMISSIONS.ADMIN_ANALYTICS,
    PERMISSIONS.ADMIN_LOGS,
    
    // System Permissions
    PERMISSIONS.SYSTEM_HEALTH,
    PERMISSIONS.SYSTEM_METRICS,
    PERMISSIONS.SYSTEM_LOGS,
  ],
  
  [ROLES.MANAGER]: [
    // User Management (limited)
    PERMISSIONS.USER_READ,
    PERMISSIONS.USER_LIST,
    PERMISSIONS.USER_INVITE,
    
    // Platform Account Management
    PERMISSIONS.ACCOUNT_CONNECT,
    PERMISSIONS.ACCOUNT_DISCONNECT,
    PERMISSIONS.ACCOUNT_READ,
    PERMISSIONS.ACCOUNT_UPDATE,
    PERMISSIONS.ACCOUNT_LIST,
    PERMISSIONS.ACCOUNT_REFRESH_TOKEN,
    
    // Content Management
    PERMISSIONS.POST_CREATE,
    PERMISSIONS.POST_READ,
    PERMISSIONS.POST_UPDATE,
    PERMISSIONS.POST_DELETE,
    PERMISSIONS.POST_PUBLISH,
    PERMISSIONS.POST_SCHEDULE,
    PERMISSIONS.POST_LIST,
    PERMISSIONS.POST_ANALYTICS,
    
    // Message Management
    PERMISSIONS.MESSAGE_READ,
    PERMISSIONS.MESSAGE_SEND,
    PERMISSIONS.MESSAGE_DELETE,
    PERMISSIONS.MESSAGE_LIST,
    PERMISSIONS.MESSAGE_AUTO_REPLY,
    PERMISSIONS.MESSAGE_TEMPLATE,
    
    // Template Management
    PERMISSIONS.TEMPLATE_CREATE,
    PERMISSIONS.TEMPLATE_READ,
    PERMISSIONS.TEMPLATE_UPDATE,
    PERMISSIONS.TEMPLATE_DELETE,
    PERMISSIONS.TEMPLATE_LIST,
    PERMISSIONS.TEMPLATE_USE,
    
    // Analytics
    PERMISSIONS.ANALYTICS_READ,
    PERMISSIONS.ANALYTICS_EXPORT,
    PERMISSIONS.ANALYTICS_REPORT,
    PERMISSIONS.ANALYTICS_DASHBOARD,
    
    // Automation
    PERMISSIONS.AUTOMATION_CREATE,
    PERMISSIONS.AUTOMATION_READ,
    PERMISSIONS.AUTOMATION_UPDATE,
    PERMISSIONS.AUTOMATION_DELETE,
    PERMISSIONS.AUTOMATION_EXECUTE,
    PERMISSIONS.AUTOMATION_LIST,
    
    // Campaign Management
    PERMISSIONS.CAMPAIGN_CREATE,
    PERMISSIONS.CAMPAIGN_READ,
    PERMISSIONS.CAMPAIGN_UPDATE,
    PERMISSIONS.CAMPAIGN_DELETE,
    PERMISSIONS.CAMPAIGN_START,
    PERMISSIONS.CAMPAIGN_PAUSE,
    PERMISSIONS.CAMPAIGN_STOP,
    PERMISSIONS.CAMPAIGN_LIST,
    
    // File Management
    PERMISSIONS.FILE_UPLOAD,
    PERMISSIONS.FILE_READ,
    PERMISSIONS.FILE_DELETE,
    PERMISSIONS.FILE_LIST,
    PERMISSIONS.FILE_DOWNLOAD,
  ],
  
  [ROLES.USER]: [
    // Platform Account Management
    PERMISSIONS.ACCOUNT_CONNECT,
    PERMISSIONS.ACCOUNT_DISCONNECT,
    PERMISSIONS.ACCOUNT_READ,
    PERMISSIONS.ACCOUNT_LIST,
    
    // Content Management
    PERMISSIONS.POST_CREATE,
    PERMISSIONS.POST_READ,
    PERMISSIONS.POST_UPDATE,
    PERMISSIONS.POST_DELETE,
    PERMISSIONS.POST_PUBLISH,
    PERMISSIONS.POST_SCHEDULE,
    PERMISSIONS.POST_LIST,
    PERMISSIONS.POST_ANALYTICS,
    
    // Message Management
    PERMISSIONS.MESSAGE_READ,
    PERMISSIONS.MESSAGE_SEND,
    PERMISSIONS.MESSAGE_LIST,
    PERMISSIONS.MESSAGE_AUTO_REPLY,
    PERMISSIONS.MESSAGE_TEMPLATE,
    
    // Template Management
    PERMISSIONS.TEMPLATE_CREATE,
    PERMISSIONS.TEMPLATE_READ,
    PERMISSIONS.TEMPLATE_UPDATE,
    PERMISSIONS.TEMPLATE_DELETE,
    PERMISSIONS.TEMPLATE_LIST,
    PERMISSIONS.TEMPLATE_USE,
    
    // Analytics
    PERMISSIONS.ANALYTICS_READ,
    PERMISSIONS.ANALYTICS_EXPORT,
    PERMISSIONS.ANALYTICS_DASHBOARD,
    
    // Automation
    PERMISSIONS.AUTOMATION_CREATE,
    PERMISSIONS.AUTOMATION_READ,
    PERMISSIONS.AUTOMATION_UPDATE,
    PERMISSIONS.AUTOMATION_DELETE,
    PERMISSIONS.AUTOMATION_EXECUTE,
    PERMISSIONS.AUTOMATION_LIST,
    
    // Campaign Management
    PERMISSIONS.CAMPAIGN_CREATE,
    PERMISSIONS.CAMPAIGN_READ,
    PERMISSIONS.CAMPAIGN_UPDATE,
    PERMISSIONS.CAMPAIGN_DELETE,
    PERMISSIONS.CAMPAIGN_START,
    PERMISSIONS.CAMPAIGN_PAUSE,
    PERMISSIONS.CAMPAIGN_STOP,
    PERMISSIONS.CAMPAIGN_LIST,
    
    // File Management
    PERMISSIONS.FILE_UPLOAD,
    PERMISSIONS.FILE_READ,
    PERMISSIONS.FILE_DELETE,
    PERMISSIONS.FILE_LIST,
    PERMISSIONS.FILE_DOWNLOAD,
    
    // Subscription Management
    PERMISSIONS.SUBSCRIPTION_READ,
    PERMISSIONS.SUBSCRIPTION_UPDATE,
    PERMISSIONS.SUBSCRIPTION_CANCEL,
    PERMISSIONS.SUBSCRIPTION_BILLING,
  ],
  
  [ROLES.VIEWER]: [
    // Read-only permissions
    PERMISSIONS.ACCOUNT_READ,
    PERMISSIONS.ACCOUNT_LIST,
    PERMISSIONS.POST_READ,
    PERMISSIONS.POST_LIST,
    PERMISSIONS.POST_ANALYTICS,
    PERMISSIONS.MESSAGE_READ,
    PERMISSIONS.MESSAGE_LIST,
    PERMISSIONS.TEMPLATE_READ,
    PERMISSIONS.TEMPLATE_LIST,
    PERMISSIONS.ANALYTICS_READ,
    PERMISSIONS.ANALYTICS_DASHBOARD,
    PERMISSIONS.AUTOMATION_READ,
    PERMISSIONS.AUTOMATION_LIST,
    PERMISSIONS.CAMPAIGN_READ,
    PERMISSIONS.CAMPAIGN_LIST,
    PERMISSIONS.FILE_READ,
    PERMISSIONS.FILE_LIST,
    PERMISSIONS.FILE_DOWNLOAD,
  ],
  
  [ROLES.API_CLIENT]: [
    // API-specific permissions
    PERMISSIONS.POST_CREATE,
    PERMISSIONS.POST_READ,
    PERMISSIONS.POST_UPDATE,
    PERMISSIONS.POST_DELETE,
    PERMISSIONS.POST_PUBLISH,
    PERMISSIONS.POST_SCHEDULE,
    PERMISSIONS.POST_LIST,
    PERMISSIONS.MESSAGE_READ,
    PERMISSIONS.MESSAGE_SEND,
    PERMISSIONS.MESSAGE_LIST,
    PERMISSIONS.ANALYTICS_READ,
    PERMISSIONS.FILE_UPLOAD,
    PERMISSIONS.FILE_READ,
    PERMISSIONS.WEBHOOK_READ,
  ],
} as const;

export const PERMISSION_CATEGORIES = {
  USER: 'user',
  ACCOUNT: 'account',
  CONTENT: 'content',
  MESSAGE: 'message',
  TEMPLATE: 'template',
  ANALYTICS: 'analytics',
  AUTOMATION: 'automation',
  CAMPAIGN: 'campaign',
  WEBHOOK: 'webhook',
  FILE: 'file',
  SUBSCRIPTION: 'subscription',
  ADMIN: 'admin',
  SYSTEM: 'system',
} as const;

export const RESOURCE_ACTIONS = {
  CREATE: 'create',
  READ: 'read',
  UPDATE: 'update',
  DELETE: 'delete',
  LIST: 'list',
  EXECUTE: 'execute',
  PUBLISH: 'publish',
  SCHEDULE: 'schedule',
  EXPORT: 'export',
  IMPORT: 'import',
  UPLOAD: 'upload',
  DOWNLOAD: 'download',
} as const;